---
title: "Data Visualization"
author: "Emily Gong"
date: "October 13, 2018"
output: 
  html_document: 
    keep_md: yes
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width=8, fig.height=8,
                      echo=FALSE, warning=FALSE, message=FALSE)
knitr::opts_knit$set(root.dir = "../")

```


```{r Load dependencies}
library(data.table)
library(ggplot2)
library(plotly)
```

```{r Load data}
data <- fread("data/life_data_sep_avg.csv", sep = ",")
survivors <- data[data$Element == "Number of survivors at age x (lx)" & data$Sex == "Both" & data$GEO == "British Columbia" ,]
lifeExp <- data[data$Element == "Life expectancy (in years) at age x (ex)" & data$Sex == "Both" & data$GEO == "British Columbia",]
```

```{r}

#Age <- survivors[,survivors$Age_group]
#LifeExp <- survivors[,survivors$AVG_VALUE]
#Year <- survivors[,survivors$YEAR]

Age <- lifeExp[,lifeExp$Age_group]
LifeExp <- lifeExp[,lifeExp$AVG_VALUE]
Year <- lifeExp[,lifeExp$YEAR]
#steps <- data.frame(seq(1980, 2016, by = 4))
#colnames(steps) <- c("1980","1984","1988","1992","1996","2000","2004","2008","2012","2016")



p <-  plot_ly(
    x = Age, 
    y = LifeExp, 
    
    frame = Year,  
    type = 'scatter',
    mode = 'lines'
  ) %>%
  
  layout(
    title = "Life Expectancy in BC (1980-2016)",
    xaxis = list(
      type = "linear",
      title = "Age"
    ),
    yaxis = list(
      title = "Life Expectancy"
    )
)

p <- p %>% 
  animation_opts(
    1000, easing = "elastic", redraw = FALSE
  )

p <- p %>% 
  animation_button(
    x = 1, xanchor = "right", y = 0, yanchor = "bottom"
  )

p

```

## 