--- 
title: "Hackseq18: Anatomy of morbidity"
author: "Eva Yap, Katarina Priecelova, Shannon Lo, Rachel Miller, Mariam Arab, chuhan zhang, Emily Gong, Sophia Chan, Adil Imtiaz,  Uyen Nguyen, Lisa Cao, Marion Shadbolt, Raissa Phillibert, Noushin Nabavi"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
biblio-style: apalike
link-citations: yes
description: "This is the compilation of our analysis of the open dataset 'Death, causes of death, and life expectancy, 2016' from Canadian Vital Statistics."
---

# Prerequisites

The **bookdown** package can be installed from CRAN or Github:

```{r eval=FALSE}
options(width = 9999)
install.packages("bookdown")
# or the development version
# devtools::install_github("rstudio/bookdown")
```

Remember each Rmd file contains one and only one chapter, and a chapter is defined by the first-level heading `#`.

To compile this example to PDF, you need XeLaTeX. You are recommended to install TinyTeX (which includes XeLaTeX): <https://yihui.name/tinytex/>.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
